### ISSUE TITLE
Importing & Exporting Halo MCC Reach Forge map into Blender

### ISSUE THREAD

**Issue by OnePurpleDuck** [Waffle1434/Halo-Reach-Forge-Assistant#17]
![Capture1](https://github.com/Waffle1434/Mjolnir-Forge-Editor/assets/174213283/6f8d2c27-1077-449d-a85e-14170701df3c)

So the long story short is that I saw this blender tool/mod you made and was hoping it could help overcome Halo Reach's forge object limit, by importing my map into blender using your tool/mod and then exporting it back. But I'm struggling to even import in the map to start with.

Hopefully someone can view the image I've attached and tell me what I'm doing wrong. Thanks to anyone that's able to help.

**Comment by ghost** [comment]
for clarities sake, there is no overcoming reach's object limit, its pretty hardcoded

as for your issue, did you extract the zip file before running it? seeing the folder name "\Temp1_Mjolnir.Forge.Editor.zip\" is concerning

**Comment by OnePurpleDuck** [comment]
Thank you Connor-jt for answering my question, I'm sad to now understand that my Halo Reach forge map will never be completed due to the games hardcoded object limit. Thank you again Connor-jt for answering.
