### ISSUE TITLE
Blender says a file is missing.

### ISSUE THREAD

**Issue by IshtoSukul** [Waffle1434/Halo-Reach-Forge-Assistant#2]
When I pull up the editor and try to play the script it will not let me. This error saying ForgeBridge.d11 is not found. I don't know how to fix it. I've gone through all the steps and downloaded all the assets but it won't work.

![error_notfound](https://user-images.githubusercontent.com/104788376/166301751-370f400d-d7f3-44f8-ae00-c30f575ab66c.PNG)

**Comment by Waffle1434** [comment]
Is `ForgeBridge.dll` next to the blend file you opened? Its included in the release zip: https://github.com/Waffle1434/Mjolnir-Forge-Editor/releases/latest

Antivirus might delete the dll as well
