### ISSUE TITLE
Importing my map to blender doesn't seem to work. What am I doing wrong?

### ISSUE THREAD

**Issue by shaymoe2** [Waffle1434/Halo-Reach-Forge-Assistant#6]
Please see 1 minute video to demonstrate my process on trying to import my map.

https://www.youtube.com/watch?v=EARKWzmj7uA

**Comment by Waffle1434** [comment]
The MCC update likely broke it, I'll try to update, sorry about that

**Comment by shaymoe2** [comment]
Ok, thanks for getting back to me! Glad it’s not something I was doing wrong 🤪
