### ISSUE TITLE
Cant find forge objects when importing

### ISSUE THREAD

**Issue by Theagent4775** [Waffle1434/Halo-Reach-Forge-Assistant#8]
i cant find it when importing
![image](https://user-images.githubusercontent.com/129519907/229134851-24b63e91-3305-42fe-a906-50591e148e82.png)

**Comment by jwoodruff40** [comment]
@Theagent4775 

I had the same issue when using the latest Blender 3.5. I downloaded Blender 3.4 from their archive and it worked fine. I used the portable version of 3.4, but I can't imagine there'd be any issues with using the install version.

**Comment by Waffle1434** [comment]
Blender 3.5+ broke the overriding of copy-paste. I've fixed it for now by ignoring the error, but that's rather annoying of you Blender.
